[package]
name = "hayaku-hashire"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
home = "0.5"
rand = "0.9"
serde = { version = "1.0", features = ["derive"] }
toml = "0"
xdg = "2.5"
