[package]
name = "tangerine-tailleferre"
version = "0.1.1"
authors = ["j39m"]
edition = "2021"

[[bin]]
name = "tt2"
path = "src/tt2.rs"

[dependencies]
chrono = "0.4"
sqlite = "0"

[dependencies.clap]
version = "4"
features = [ "cargo", "derive" ]
