[package]
name = "tangerine-tailleferre"
version = "0.1.1"
authors = ["j39m"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"

[dependencies.clap]
version = "4"
features = [ "cargo" ]
