[package]
name = "tangerine-tailleferre"
version = "0.1.1"
authors = ["j39m"]
edition = "2021"

[[bin]]
name = "tangerine-tailleferre"
path = "src/main.rs"

[dependencies]
chrono = "0.4"

[dependencies.clap]
version = "4"
features = [ "cargo" ]
