#!/usr/bin/env python3
"""
sanity check for colors.c
"""

import sys
import itertools


def main(*args):

    COLORS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

    numColors = int(args[1])
    numConsec = int(args[2])
    listLen =   int(args[3])

    excludes = [letter*(numConsec+1) for letter in COLORS]
    COLORS = COLORS[:numColors]

    validSequences = []
    for pr in itertools.product(COLORS, repeat=listLen):
        noGood = False
        pr = "".join(pr)
        for consec in excludes:
            if consec in pr:
                noGood = True
                break
        if not noGood:
            validSequences.append(pr)

    print(len(validSequences))
    return 0


if __name__ == "__main__":
    retv = main(*sys.argv)
    sys.exit(retv)
