[package]
name = "xkpw"
version = "0.1.2"
authors = ["j39m"]
edition = "2024"

[dependencies]
rand = "0"

[dependencies.clap]
version = "4"
features = [ "cargo", "derive" ]

[[bin]]
name = "xkpw"
path = "main.rs"
